blog_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('blog/', include('blogs.urls')),
]

blogs/urls.py
from django.urls import path
from blogs.views import PostFeed, PostListView, PostDetailView, PostCreateView, ReadMarkView

app_name = 'blogs'

urlpatterns = [
    path('feed/', PostFeed.as_view(), name='feed'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('', PostListView.as_view(), name='posts'),
    path('post/<int:pk>/read-mark/', ReadMarkView.as_view(), name='read_mark'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users.views import BlogersView, SubscribeView

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('blogers/', BlogersView.as_view(), name='blogers'),
    path('subscribe/<int:pk>/', SubscribeView.as_view(), name='subscribe'),
]

blogs/models.py
from django.db import models
from users.models import User
from django.urls import reverse


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created date')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated date')

    class Meta:
        abstract = True


class Blog(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='blog_user')
    subscribers = models.ManyToManyField(
        User, blank=True,
        verbose_name='Blog\'s subscribers',
        related_name='user_subscribers'
    )
    title = models.CharField(max_length=255, verbose_name='Blog title')

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        verbose_name = 'User blog'
        verbose_name_plural = 'User blogs'
        ordering = ('-created', )


class Post(TimeStampedModel):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=255, verbose_name='Post title')
    text = models.TextField()

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        verbose_name = 'Blog post'
        verbose_name_plural = 'Blog posts'
        ordering = ('-updated', )

    def get_absolute_url(self):
        return reverse('blogs:post_detail', args=(self.pk, ))


class ReadMark(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='read_marks')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='read_marks')
    is_marked = models.BooleanField(default=True)

    def __str__(self):
        return '{}-{}'.format(self.user.username, self.post.title)

    class Meta:
        verbose_name = 'Post read mark'
        verbose_name_plural = 'Post read marks'
        unique_together = ('user', 'post', )
        ordering = ('-updated', )

users/models.py
from django.db import models

from django.contrib.auth.models import User

blogs/forms.py
from django import forms

from blogs.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'text',
        )

blogs/views.py
from django.views.generic import ListView, CreateView, DetailView, View
from blogs.models import Post, Blog, ReadMark
from blogs.forms import PostForm
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse


class PostFeed(ListView):
    template_name = 'blogs/feed.html'
    context_object_name = 'feeds'
    model = Post
    ordering = ('-updated', )

    def get_queryset(self):
        user = self.request.user
        return Post.objects.filter(blog__in=user.user_subscribers.all())

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['marked'] = ReadMark.objects.filter(user=self.request.user).values_list('post', flat=True)
        return context


class PostListView(ListView):
    template_name = 'blogs/own_posts.html'
    context_object_name = 'posts'
    model = Post
    ordering = ('-updated', )

    def get_queryset(self):
        return Post.objects.filter(blog__user=self.request.user)


class PostCreateView(CreateView):
    form_class = PostForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.blog = self.request.user.blog_user
        obj.save()
        ReadMark.objects.create(
            user=self.request.user,
            post=obj
        )
        return super(PostCreateView, self).form_valid(form)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blogs/post_detail.html'
    context_object_name = 'post'


class ReadMarkView(View):
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))
        read_mark, _ = ReadMark.objects.get_or_create(
            user=request.user,
            post=post,
        )
        return HttpResponseRedirect(reverse('blogs:feed'))

users/views.py
from django.views.generic import ListView, View
from users.models import User
from blogs.models import Blog, ReadMark, Post
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import transaction


class BlogersView(ListView):
    template_name = 'blogs/blogers.html'
    model = User
    context_object_name = 'blogers'

    def get_queryset(self):
        return User.objects.exclude(pk=self.request.user.id)


class SubscribeView(View):
    def post(self, request, *args, **kwargs):
        blog = get_object_or_404(Blog, pk=self.kwargs.get('pk'))
        if request.user in blog.subscribers.all():
            with transaction.atomic():
                blog.subscribers.remove(request.user)
                print(blog.posts.all())
                print(ReadMark.objects.filter(
                    user=self.request.user,
                    post__in=blog.posts.all(),
                ))
                ReadMark.objects.filter(
                    user=self.request.user,
                    post__in=blog.posts.all(),
                ).delete()
        else:
            blog.subscribers.add(request.user)
        return HttpResponseRedirect(reverse('users:blogers'))

templates/base.html
{% load static %}

<head>
{% block head %}

{% endblock head %}
</head>

{% block header %}

{% endblock header %}

{% block content %}

{% endblock content %}

{% block footer %}

{% endblock footer %}

templates/blogs/blogers.html
{% extends 'index.html' %}

{% block content %}

    <h1 align="center"> Blogers</h1>
    <div class="container">
        <div class="row">
            {% for bloger in blogers %}
                <div class="col-lg-4">
                <h2>{{ bloger.username }}</h2>
                <p>{{ bloger.blog_user }}.</p>
                    <form action="{% url 'users:subscribe' bloger.blog_user.id %}" method="post">
                    {% csrf_token %}
                        {% if request.user in bloger.blog_user.subscribers.all %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                Unsubscribe
                            </button>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                Subscribe
                            </button>
                        </div>
                    {% endif %}
                    </form>
                </div>

            {% endfor %}

        </div>
    </div>

{% endblock content %}

templates/blogs/feed.html
{% extends 'index.html' %}
{% load  static %}

{% block content %}
    <div class="container">
    <h1 align="center">FEED</h1>
        <div class="row">
            {% for post in feeds %}
                <div class="col-lg-4">
                    <h2>{{ post.title }}</h2>
                        <p>{{ post.updated }}</p>
                        <p>{{ post.text|slice:":255" }}...</p>
                        {% if post.id in marked %}
                            <p style="color:gray">Readed</p>
                        {% else %}
                            <form action="{% url 'blogs:read_mark' post.pk %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success">
                                        Subscribe
                                    </button>
                                </div>
                            </form>
                        {% endif %}
                    <p><a class="btn btn-primary" href="{% url 'blogs:post_detail' post.pk %}" role="button">View details »</a></p>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock content %}

templates/blogs/own_posts.html
{% extends 'index.html' %}
{% load  static %}

{% block content %}
    <div class="container">
        <div class="row">

            <div class="col-md-8 col-md-offset-2">

                <h1>Create post</h1>

                <form action="{% url 'blogs:post_create' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">Title <span class="require">*</span></label>
                        <input type="text" class="form-control" name="title" required/>
                    </div>

                    <div class="form-group">
                        <label for="description">Content</label>
                        <textarea rows="5" class="form-control" name="text" required ></textarea>
                    </div>

                    <div class="form-group">
                        <p><span class="require">*</span> - required fields</p>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            Create
                        </button>
                    </div>

                </form>
            </div>

        </div>
    </div>
    <h1 align="center"> My posts</h1>
    <div class="container">
        <div class="row">
            {% for post in posts %}
                <div class="col-lg-4">
                <h2>{{ post.title }}</h2>
                <p>{{ post.text|slice:":255" }}...</p>
                <p><a class="btn btn-primary" href="{% url 'blogs:post_detail' post.pk %}" role="button">View details »</a></p>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock content %}

templates/blogs/post_detail.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <div class="col-md-12">
        <h1>{{ post.title }}</h1>
        <p>{{ post.text }}</p>
        <div>
            <span class="badge">Posted {{ post.updated }}</span>
        </div>
    </div>
</div>
{% endblock content %}

templates/blogs/qwe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block head %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <title>Blog</title>
{% endblock head %}

{% block header %}

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blogs:posts' %}">Personal blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'blogs:feed' %}">Feed</a></li>
          </ul>
            <ul class="nav navbar-nav">
            <li><a href="{% url 'users:blogers' %}">Blogers</a></li>
          </ul>

          <ul class="nav navbar-nav n   avbar-right">
            <li><a href="{% url 'users:logout' %}">Logout</a></li>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

{% endblock %}